---
root: true

extends: eslint:recommended

parserOptions:
  ecmaVersion: 2017

env:
  browser: true,
  node: true,
  es6: true

rules:
  no-console: warn
  indent:
    - error
    - 2
    - SwitchCase: 1
  quotes:
    - error
    - single
    - avoidEscape: true
  linebreak-style: [ error, unix ]
  semi: [ error, always ]
  no-var: error
  comma-dangle: [ error, always-multiline ]
  func-call-spacing: [ error, never ]
  prefer-arrow-callback: error
  arrow-spacing:
    - error
    - before: true
      after: true
  space-before-function-paren:
    - error
    - named: never
      anonymous: never
      asyncArrow: always
  space-infix-ops: error
  new-parens: error
  no-whitespace-before-property: error
  no-useless-concat: error
